[tool.black]
line-length = 120
target-version = ['py39']
# include = '\.pyi?$'
extend-exclude = '''
/(
  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
  | profiling
  | .+/migrations
)/
'''
multi_line_output = 4
multi-line = 4
force-grid-wrap = 4
include_trailing_comma = true
use_parentheses = true
ensure_newline_before_comments = false
combine_as_imports = true
lines_after_imports = 2
force_alphabetical_sort = true


[tool.flake8]
ignore = "E226"
max-line-length = 120
exclude = "tests/*,*/migrations/*"
max-complexity = 10

[tool.mypy]
python_version = "3.9"
ignore_missing_imports = "True"